# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\":\n\x08TodoItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x1f\n\x0cTodoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x14\n\x06TodoId\x12\n\n\x02id\x18\x01 \x01(\t\")\n\x08TodoList\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.todo.TodoItem\"\x07\n\x05\x45mpty2\x95\x01\n\x0bTodoService\x12-\n\x07\x41\x64\x64Todo\x12\x0e.todo.TodoItem\x1a\x12.todo.TodoResponse\x12\'\n\x08GetTodos\x12\x0b.todo.Empty\x1a\x0e.todo.TodoList\x12.\n\nDeleteTodo\x12\x0c.todo.TodoId\x1a\x12.todo.TodoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODOITEM']._serialized_start=20
  _globals['_TODOITEM']._serialized_end=78
  _globals['_TODORESPONSE']._serialized_start=80
  _globals['_TODORESPONSE']._serialized_end=111
  _globals['_TODOID']._serialized_start=113
  _globals['_TODOID']._serialized_end=133
  _globals['_TODOLIST']._serialized_start=135
  _globals['_TODOLIST']._serialized_end=176
  _globals['_EMPTY']._serialized_start=178
  _globals['_EMPTY']._serialized_end=185
  _globals['_TODOSERVICE']._serialized_start=188
  _globals['_TODOSERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
